### ISSUE TITLE
[Quest 1] Joysticks are not being tracked

### ISSUE THREAD

**Issue by kisatoto** [DaXcess/CWVR#12]
I'm using the Quest 1 on the SteamVR on the oculus_win7and8 - v1.15.12 beta which allows the use of older oculus software.

Triggers seem to work as I am able to recalibrate, click, and jump. However, it appears that the joysticks are not being tracked as when using the joysticks I kind of just am stuck in place and am not able to rotate or move.

It would be nice if this could get fixed, however, I also understand that since this is older software if there will not be a fix for this bug in the future.

**Comment by DaXcess** [comment]
Outdated software sounds like the issue here, if the tracking data sent to Unity does not match expected values then it will straight up just not work
