### ISSUE TITLE
unable to invite people

### ISSUE THREAD

**Issue by Thatlocalslime** [DaXcess/CWVR#13]
im in vr and the invite friends menu wont pop up (using quest 3)

**Comment by DaXcess** [comment]
Inviting is done through Steam. If steam doesn't work or you're not using SteamVR (I don't even know if SteamVR has an invite menu though) then the button does nothing or only does stuff on PC

**Comment by Thatlocalslime** [comment]
it acts like i haven't even opened the game and only gives me the choice to "launch game"

**Comment by DaXcess** [comment]
This is an issue with Steam, CWVR has no custom inviting
