### ISSUE TITLE
Cant change controls

### ISSUE THREAD

**Issue by CoolCrow638** [DaXcess/CWVR#17]
![Uploading Снимок экрана (308).png…]()
i turn on "EnableCustomControls", and try to change "CustomControls" to "WMR" or "wmr" and this does not work :(

**Comment by CoolCrow638** [comment]
crap

**Comment by DaXcess** [comment]
You're not supposed to edit the CustomControls field, the mod does that for you.

'wmr' is also invalid, custom controls look more something like '{"Movement":{"controller":1,"axis":0},"etc...":{...}}'

CWVR is not LCVR, CWVR does not have controller profiles like that.

**Comment by CoolCrow638** [comment]
> You're not supposed to edit the CustomControls field, the mod does that for you.
> 
> 'wmr' is also invalid, custom controls look more something like '{"Movement":{"controller":1,"axis":0},"etc...":{...}}'
> 
> CWVR is not LCVR, CWVR does not have controller profiles like that.


- But, when I turn on this setting only, all the buttons on the controller stop working

**Comment by DaXcess** [comment]
There's a hotfix available in 172c82c84785e4895353331e0fee7f32815648f7.
Keep in mind you have changed "Internal" settings using TMM, which is not intended. You should only change these settings from the in game settings menu (VR Settings, Controls).

**Comment by Ihrychov** [comment]
> There's a hotfix available in [172c82c](https://github.com/DaXcess/CWVR/commit/172c82c84785e4895353331e0fee7f32815648f7). Keep in mind you have changed "Internal" settings using TMM, which is not intended. You should only change these settings from the in game settings menu (VR Settings, Controls).

 I haven't that option in the "VR Setting"

**Comment by DaXcess** [comment]
The VR controls has taken over the original games controls. They are not under VR Controls.

**Comment by Ihrychov** [comment]
> The VR controls has taken over the original games controls. They are not under VR Settings.
> 
> If the VR Settings tab is not visible remove potential conflicting mods, until those issues have been

And under "Controls" I haven't "VR control"

**Comment by TinyDerp** [comment]
This error might give you an idea on how to fix the VR setting not showing up. Btw for some of us (that icludes me) the ocules controller settings are enaugh so take your time man. 👍
![image](https://github.com/DaXcess/CWVR/assets/83468889/5daee1dd-e03b-4a67-a66b-39e252e34ee2)
