### ISSUE TITLE
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Lukww** [DaXcess/CWVR#3]
Not sure if this is an error on my end or with the code and how early and unstable it is right now but when I try to boot up the game with the mod installed, it just gives me the error in the title.

**[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
CursorHandler.Update () (at <c561fa8d81824a1aa363bc42554b44c5>:0)**

I'll link the log as well. It looks like the mod kind of loaded but failed halfway through.

[LogOutput.log](https://github.com/DaXcess/CWVR/files/15134508/LogOutput.log)

I'm pretty sure I compiled the thing correctly, I basically did the same thing I did for the LCVR mod and that worked.

**Comment by DaXcess** [comment]
That's an issue outside of CWVR inside Unity.InputSystem that is caused by a broken dependency tree. Nothing that CWVR can do about since it means that you've packaged the mod incorrectly.

**Comment by Lukww** [comment]
> That's an issue outside of CWVR inside Unity.InputSystem that is caused by a broken dependency tree. Nothing that CWVR can do about since it means that you've packaged the mod incorrectly.

So apparently, the place where I was getting the files ([here](https://github.com/DaXcess/LCVR/releases)) didn't have Unity.InputSystem.dll. I downloaded it and it works perfectly now. 👍 (very fun btw)
