### ISSUE TITLE
Some bugs i found while playing with this mod

### ISSUE THREAD

**Issue by wolfifurr** [DaXcess/CWVR#4]
I tried to play with this mod with my HTC Vive Pro. These are the bugs I discovered:

1. The jump button is missing, and up and down touchpad buttons on the right controller are crouching.
2. The only method to access the main screen or exit is to rejoin; the menu buttons have no function for me.
3. Occasionally, I see the computer overlay blinking on my screen.
4. I have to manually select slots on my keyboard instead of being able to choose with controllers VR.

That appears to be all that I could find. I hope you can fix these. Really awesome mod.

**Comment by DaXcess** [comment]
1, 2 and 4 are because the mod only supports the basic ABXY controller scheme (old Unity InputSystem), 3 is because of the state of the mod (early, screenspace UI has not yet been disabled for VR)

**Comment by wolfifurr** [comment]
> 1, 2 and 4 are because the mod only supports the basic ABXY controller scheme (old Unity InputSystem), 3 is because of the state of the mod (early, screenspace UI has not yet been disabled for VR)

I not quite understand what to do to fix it myself. What do I need to do to make ABXY controller scheme work on my controllers or is its mod technical side issue?

**Comment by DaXcess** [comment]
The controls are hardcoded 
https://github.com/DaXcess/CWVR/blob/e15cfb22c4b20463f3800ef12f491cec53d70305/Source/Input/Controls.cs#L13-L66

**Comment by DaXcess** [comment]
Control rebinding support has been added
