### ISSUE TITLE
Missing runtime dependency

### ISSUE THREAD

**Issue by BlackHawkCJ** [DaXcess/CWVR#5]
When getting runtime dependencies from LCVR it doesn't have Unity.InputSystem.dll, which causes CWVR to just not work without it

**Comment by DaXcess** [comment]
That makes sense? They are two different games, they need different code.

**Comment by BlackHawkCJ** [comment]
> That makes sense? They are two different games, they need different code.

Yes, but when retrieving dependencies in the install guide you suggest getting them from LCVR, which doesn't have the above mentioned dependency

**Comment by DaXcess** [comment]
The README.md is a copy-paste of LCVR which has already been fixed in 8f76067b633573d0f0514165e59441f8f652dd32
