### ISSUE TITLE
BepInEx 5.4.22 doesn't work for the mod

### ISSUE THREAD

**Issue by TenableRelic90** [DaXcess/CWVR#6]
Tried installing different versions of BepInEx but I get errors when opening the game and the mod doesn't work. When using 5.4.22, nothing happens, and the mod still doesn't work but I can't move in-game either.

Edit: I think the update for CW broke the mod, can't get it to work.

**Comment by DaXcess** [comment]
These we're issues from before release, presumed fixed now that CWVR is out
