### ISSUE TITLE
CWVR only launches in a big screen in steam vr

### ISSUE THREAD

**Issue by Sandrone212** [DaXcess/CWVR#8]
when i go to launch the game it only launches in the big screen in steam vr. I have tried to fix this issue for the past hour but haven't found a solution. any fixes?

**Comment by DaXcess** [comment]
Best bet is to play around with the OpenXR setting (first setting) until one of them works

**Comment by WeXetProgram** [comment]
I found this issue on mine too, i managed to fix it by copying the openXR files on content warning plugin directory to the mod profile (in case you're using Thunderstore)
