### ISSUE TITLE
WMR issue

### ISSUE THREAD

**Issue by Ihrychov** [DaXcess/CWVR#9]
Too much buttons on WMR doesn't work

**Comment by DaXcess** [comment]
> At the moment, CW // VR only supports Oculus styled controller layouts (ABXY-based). For more detailed controls, check out the controls [wiki page](https://thunderstore.io/c/content-warning/p/DaXcess/CWVR/wiki) on Thunderstore.

**Comment by DaXcess** [comment]
Fixed in ba651cf13f495b123ebb89490e22583fe6ac30ac (added controller rebinding support)
